### ISSUE TITLE
Uploading blobs for Google Keep notes

### ISSUE THREAD

**Issue by andrii-minchekov** [rukins/gkeepapi-java#1]
This tool would be invaluable if it supports uploading blobs. It's really a show-stopper.
If you know could you please provide more information on how "upload blobs" API looks on Google side? I think having described the server contract of this unofficial API will speedup the client development with this crucial feature. I am ready to help with the implementation of this feature.

**Comment by rukins** [comment]
I am glad that you are interested in it, thank you! Yeah, it is indeed important feature. i was going to implement the uploading blobs a little later. But if you want to help, your help is welcomed.
Give me a few hours and i will describe the server contract. I will add it as the project file.

**Comment by rukins** [comment]
@andrii-minchekov, the file where i described all requests to the server is ready. See [here](https://github.com/rukins/gkeepapi-java/blob/master/server-endpoints.md).
Please ask any questions you have

**Comment by rukins** [comment]
@andrii-minchekov, it is now available to upload images and pull it from the server. You can test it :)
